#!/bin/bash
set -euo pipefail

. ./scripts/library.sh

cat ./apps/whoa/main.go
pause

pushd ./apps/whoa
docker build -t nfontes/whoa:latest .
docker push nfontes/whoa:latest
popd
pause

cat ./manifests/10-test-gvisor-service.yaml
pause

kubectl apply -n customers -f ./manifests/10-test-gvisor-service.yaml
kubectl wait --timeout=180s -n customers --for=condition=ready ksvc/whoa
kubectl get ksvc -n customers whoa \
  --output=custom-columns=NAME:.metadata.name,URL:.status.url
